export const lang = {
  en: {
    search: "Search",
    GptSearchLang:
      "Search movies, genres, or describe what you want to watch...",
    GptSearchHeading: "Discover Movies with AI",
    GptSearchh2:
      "Search and filter movies using natural language powered by GPT",
    filters: "Filters",
    genre: "Genre",
    year: "Year",
    rating: "Rating",
    sortBy: "Sort By",
    allGenres: "All Genres",
    action: "Action",
    comedy: "Comedy",
    drama: "Drama",
    horror: "Horror",
    romance: "Romance",
    sciFi: "Sci-Fi",
    allYears: "All Years",
    allRatings: "All Ratings",
    relevance: "Relevance",
    popularity: "Popularity",
    latest: "Latest",
    searchResults: "Search Results",
  },
  hn: {
    search: "खोज",
    GptSearchLang:
      "फ़िल्मों, शैलियों को खोजें या आप जो देखना चाहते हैं उसका वर्णन करें...",
    GptSearchHeading: "एआई की मदद से फिल्में खोजें",
    GptSearchh2:
      "GPT द्वारा संचालित प्राकृतिक भाषा का उपयोग करके फिल्मों को खोजें और फ़िल्टर करें",
    filters: "फ़िल्टर",
    genre: "शैली",
    year: "वर्ष",
    rating: "रेटिंग",
    sortBy: "इसके अनुसार क्रमबद्ध करें",
    allGenres: "सभी शैलियाँ",
    action: "एक्शन",
    comedy: "कॉमेडी",
    drama: "ड्रामा",
    horror: "हॉरर",
    romance: "रोमांस",
    sciFi: "साइ-फाई",
    allYears: "सभी वर्ष",
    allRatings: "सभी रेटिंग",
    relevance: "प्रासंगिकता",
    popularity: "लोकप्रियता",
    latest: "नवीनतम",
    searchResults: "खोज परिणाम",
  },
  sp: {
    search: "Buscar",
    GptSearchLang: "Busca películas, géneros o describe lo que quieres ver...",
    GptSearchHeading: "Descubre películas con IA",
    GptSearchh2:
      "Busque y filtre películas usando lenguaje natural con tecnología GPT",
    filters: "Filtros",
    genre: "Género",
    year: "Año",
    rating: "Clasificación",
    sortBy: "Ordenar por",
    allGenres: "Todos los géneros",
    action: "Acción",
    comedy: "Comedia",
    drama: "Drama",
    horror: "Terror",
    romance: "Romance",
    sciFi: "Ciencia ficción",
    allYears: "Todos los años",
    allRatings: "Todas las clasificaciones",
    relevance: "Relevancia",
    popularity: "Popularidad",
    latest: "Más reciente",
    searchResults: "Resultados de búsqueda",
  },
};

export const SUPPORTED_LANGUAGES = [
  { identifier: "en", name: "English" },
  { identifier: "hn", name: "hindi" },
  { identifier: "sp", name: "spanish" },
];
